### ISSUE TITLE
Crash zombie infection

### ISSUE THREAD

**Issue by omagadsamsa** [touchHLE/touchHLE#326] opened 2024-06-25 02:04 UTC
![IMG_20240625_050208](https://github.com/touchHLE/touchHLE/assets/149837198/c88ac85c-bcfb-4faa-804d-e27c26162b6b)

**Comment by ciciplusplus** [comment] 2024-06-25 09:10
@omagadsamsa You're continue to create low-effort issues/comments in this repository...

The "good" crash report would contain:

- The version of touchHLE
- The version of app
- The logs indicating the crash
- If applicable, the save file

Does your report have any of those? No.
Do you even impacted by the issue reported? No, it's someone else being affected. You just saw a random complain and decided it's worth to bother us.

As you continue to create noise in the repository and was already warned before, I'm finally banning you here. You could try to appeal by writing an email to me explain why I should bother to unban you.

Regarding the issue itself, I cannot reproduce on my side and thus closing as "can't repro".
If someone else have more details, I'll re-open it.

**Closed by ciciplusplus** 2024-06-25 09:10 UTC
